// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfzmrvryhppsjzclnpoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxmem1ydnJ5aHBwc2p6Y2xucG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MDY3NDQsImV4cCI6MjA3NDk4Mjc0NH0.foz7FR1G8VYOvcwnMUBj3bsTGoMZrI9cmh7TofX6gjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});